import { describe, it, expect } from 'vitest';
import { extractTitle } from '../src/pipeline/title.js';

describe('extractTitle', () => {
  it('取第一条 user 消息的字符串内容', () => {
    expect(
      extractTitle([
        { role: 'assistant', content: '先开口' },
        { role: 'user', content: '帮我看看这个 bug' },
      ]),
    ).toBe('帮我看看这个 bug');
  });

  it('content 为数组时拼接 text 块', () => {
    expect(
      extractTitle([
        {
          role: 'user',
          content: [
            { type: 'text', text: '第一段' },
            { type: 'image' },
            { type: 'text', text: '第二段' },
          ],
        },
      ]),
    ).toBe('第一段 第二段');
  });

  it('折叠连续空白并截断到 200 字符', () => {
    const long = 'a'.repeat(150) + ' \n\t ' + 'b'.repeat(150);
    const t = extractTitle([{ role: 'user', content: long }]);
    expect(t).not.toMatch(/\s{2,}/);
    expect(t.length).toBeLessThanOrEqual(200);
  });

  it('无 user 消息或空白内容时返回（无标题）', () => {
    expect(extractTitle([{ role: 'assistant', content: 'x' }])).toBe('（无标题）');
    expect(extractTitle([{ role: 'user', content: '  \n ' }])).toBe('（无标题）');
  });

  it('剥除 system-reminder 等注入噪声块，保留用户实际问题', () => {
    expect(
      extractTitle([
        {
          role: 'user',
          content:
            '<system-reminder>SessionStart hook additional context: lots of noise here</system-reminder>\n帮我修复登录 bug',
        },
      ]),
    ).toBe('帮我修复登录 bug');
  });

  it('剥除命令回显与未闭合的尾部噪声标签', () => {
    expect(
      extractTitle([
        {
          role: 'user',
          content:
            '<command-name>/model</command-name><command-message>切换模型</command-message><local-command-stdout>ok</local-command-stdout>',
        },
      ]),
    ).toBe('（无标题）');
    expect(
      extractTitle([
        { role: 'user', content: '<task-notification>后台任务完成</task-notification>\n继续刚才的重构' },
      ]),
    ).toBe('继续刚才的重构');
    // 截断场景：reminder 未闭合也算噪声
    expect(
      extractTitle([{ role: 'user', content: '<system-reminder>被截断的 hook 上下文...' }]),
    ).toBe('（无标题）');
  });

  it('去掉 Caveat 提示行', () => {
    expect(
      extractTitle([
        {
          role: 'user',
          content:
            'Caveat: the messages below were generated by the user while running local commands.\n这个函数怎么写',
        },
      ]),
    ).toBe('这个函数怎么写');
  });

  it('首条 user 消息剥噪后为空时，向后找第一条有效消息', () => {
    expect(
      extractTitle([
        {
          role: 'user',
          content: [
            { type: 'text', text: '<command-name>/clear</command-name>' },
            { type: 'text', text: '<local-command-stdout>done</local-command-stdout>' },
          ],
        },
        { role: 'assistant', content: '好' },
        { role: 'user', content: '真正的提问' },
      ]),
    ).toBe('真正的提问');
  });

  it('tool_result -only 的 user 消息不作为标题来源', () => {
    expect(
      extractTitle([
        { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't1', content: '结果' }] },
        { role: 'user', content: '下一个问题' },
      ]),
    ).toBe('下一个问题');
  });
});
